server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html index.htm;

    location = /robots.txt {
        try_files $uri =404;
        access_log off;
        log_not_found off;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html =404;
    }
    include /etc/nginx/extra-conf.d/*.conf;
}
